<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <RootNamespace>Tests</RootNamespace>
    <LangVersion>10</LangVersion>
    <AssemblyName>Tests</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ApprovalTests" Version="5.7.1" />
    <PackageReference Include="Autofac.Extensions.DependencyInjection" Version="8.0.0" />
    <PackageReference Include="FluentAssertions" Version="6.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="6.0.12" />
    <PackageReference Include="Microsoft.AspNetCore.TestHost" Version="6.0.12" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="6.0.12" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.0.0" />
    <PackageReference Include="nsubstitute" Version="4.2.2" />
    <PackageReference Include="Serilog.Sinks.XUnit" Version="2.0.4" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="6.25.1" />
    <PackageReference Include="TestStack.Dossier" Version="4.0.0" />
    <PackageReference Include="xunit" Version="2.4.1" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.4.3">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="coverlet.collector" Version="3.1.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\api\api.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Features\ActivityFeed\ActivityFeedControllerTests.Get.approved.json">
      <ParentFile>$([System.String]::Copy('%(FileName)').Split('.')[0])</ParentFile>
      <ParentExtension>$(ProjectExt.Replace('proj', ''))</ParentExtension>
      <DependentUpon>ActivityFeedControllerTests.cs</DependentUpon>
    </None>
    <None Update="Features\Injury\SubmitHazardFormToSalesforceTests.SubmitSuccess.approved.json">
      <ParentExtension>.cs</ParentExtension>
      <ParentFile>SubmitHazardFormToSalesforceTests</ParentFile>
      <DependentUpon>SubmitHazardFormToSalesforceTests.cs</DependentUpon>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Plumbing\JwtBearerPostConfigureOptions.cs">
      <DependentUpon>IgnorePropertiesResolver.cs</DependentUpon>
    </Compile>
  </ItemGroup>
  
</Project>