<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Tests</RootNamespace>
    <LangVersion>12</LangVersion>
    <AssemblyName>Tests</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ApprovalTests" Version="6.0.0" />
    <PackageReference Include="FluentAssertions" Version="6.12.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="8.0.6" />
    <PackageReference Include="Microsoft.AspNetCore.TestHost" Version="8.0.6" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="8.0.6" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.10.0" />
    <PackageReference Include="nsubstitute" Version="5.1.0" />
    <PackageReference Include="Serilog.Sinks.XUnit" Version="3.0.5" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="7.6.2" />
    <PackageReference Include="TestStack.Dossier" Version="4.0.0" />
    <PackageReference Include="Verify.Xunit" Version="25.0.4" />
    <PackageReference Include="xunit" Version="2.8.1" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="coverlet.collector" Version="6.0.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\api\api.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Features\ActivityFeed\ActivityFeedControllerTests.Get.approved.json">
      <ParentFile>$([System.String]::Copy('%(FileName)').Split('.')[0])</ParentFile>
      <ParentExtension>$(ProjectExt.Replace('proj', ''))</ParentExtension>
      <DependentUpon>ActivityFeedControllerTests.cs</DependentUpon>
    </None>
    <None Update="Features\Injury\SubmitHazardFormToSalesforceTests.SubmitSuccess.approved.json">
      <ParentExtension>.cs</ParentExtension>
      <ParentFile>SubmitHazardFormToSalesforceTests</ParentFile>
      <DependentUpon>SubmitHazardFormToSalesforceTests.cs</DependentUpon>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Plumbing\JwtBearerPostConfigureOptions.cs">
      <DependentUpon>IgnorePropertiesResolver.cs</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Features\Example\v1\Model\" />
  </ItemGroup>
  
</Project>